server:
  port: 8086

# 文件上传配置
file:
  upload-dir: ./uploads/avatars

# JWT 配置
jwt:
  secret: "aVeryStrongAndLongSecretKeyForThisTextGameDemoProjectThatIsSecure"
  expiration-ms: 3600000

# DeepSeek API 配置
deepseek:
  api:
    url: https://api.deepseek.com/v1
    key: sk-bdef1b7fc01b4addb3aaf2b19ca9e662

# OpenAlex API 配置
openalex:
  api:
    url: https://api.openalex.org

# Spring 配置
spring:
  security:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/text_game_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 配置
  jpa:
    hibernate:
      # (最终修复)
      # 设置为 "validate"，Hibernate 将只检查表结构是否匹配
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect